name: Build Plugins

on: [push, pull_request]

jobs:
  build:
    runs-on: [windows-latest]

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Clone Plugins
        uses: actions/checkout@v2

      - name: Build Plugins
        run: dotnet publish -c Release src/Artemis.Plugins.HardwareMonitors.sln

        #msbuild is dumb so we have to upload one at a time :)
        #https://github.com/dotnet/sdk/issues/7238

      - name: Upload Aida64
        uses: actions/upload-artifact@v2
        with:
          name: Aida64
          path: src/Artemis.Plugins.HardwareMonitors.Aida64/bin/x64/Release/net8.0/publish

      - name: Upload HWiNFO64
        uses: actions/upload-artifact@v2
        with:
          name: HWiNFO64
          path: src/Artemis.Plugins.HardwareMonitors.HWiNFO64/bin/x64/Release/net8.0/publish

      - name: Upload OpenHardwareMonitor
        uses: actions/upload-artifact@v2
        with:
          name: OpenHardwareMonitor
          path: src/Artemis.Plugins.HardwareMonitors.OpenHardwareMonitor/bin/x64/Release/net8.0/publish

      - name: Upload Standalone
        uses: actions/upload-artifact@v2
        with:
          name: Standalone
          path: src/Artemis.Plugins.HardwareMonitors.Standalone/bin/x64/Release/net8.0-windows/publish
