name: Build Plugins

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Plugins
        uses: actions/checkout@v4

      - name: Build Plugins
        run: dotnet publish -c Release src

      - name: Install Plugin Uploader
        run: dotnet tool install ArtemisRGB.Tools.PluginUploader --global

      - name: Upload
        if: github.ref == 'refs/heads/master'
        run: artemis-plugin-uploader upload-all --pat ${{ secrets.WORKSHOP_PAT }} --folder src